# Generated by Django 3.1.5 on 2021-02-10 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210205_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 2, 10)),
        ),
    ]
