# Generated by Django 3.1.5 on 2021-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_profile_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sale',
        ),
        migrations.AddField(
            model_name='products',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
